import React , {useContext, useEffect, useState} from 'react';
// import { useFrappeAuth } from 'frappe-react-sdk';
import { locateContext } from "./App";
import { useNavigate } from "react-router-dom";

// import Button from '@mui/material/Button';
import InputLabel from '@mui/material/InputLabel';
import FormControl from '@mui/material/FormControl';
import Select from '@mui/material/Select';
import MenuItem from '@mui/material/MenuItem';
// import { RiTimeLine } from 'react-icons/ri';





// interface Role {
//   role: string; // Assuming role is a string, adjust it according to your data structure
//   // Add other properties if there are any
// }

interface PackagingRequest {
  name: string;
  employee_id: string;
  employee_name: string;
  package_type: string;
  status: string;
  purpose: string;
  transport_from: string;
  transport_to: string;
  transport_mode: string;
  packer_name: string;
  image_1: any;
  image_2:any;
  image_3:any;
  image_4:any;
  image_5:any;
  image_6:any;
  reports_to:string;
  created_request_date:string;
  created_request_time:string;
  dashboard_status:string;
    ground_check_list_1: any,
    ground_check_list_2: any,
    ground_check_list_3: any,
    ground_check_list_4: any,
    ground_check_list_5: any,
    ground_check_list_6: any,
    ground_check_list_7: any,
    ground_check_list_8: any,
    ground_check_list_9: any,
    ground_check_list_10: any,
    ground_check_list_11: any,
    ground_check_list_12: any,



    flight_check_list_1: any,
    flight_check_list_2: any,
    flight_check_list_3: any,
    flight_check_list_4: any,
    flight_check_list_5: any,
    flight_check_list_6: any,
    flight_check_list_7: any,
    flight_check_list_8: any,
    flight_check_list_9: any,
    flight_check_list_10: any,
    flight_check_list_11: any,
    flight_check_list_12: any,
    flight_check_list_13: any,
    flight_check_list_14: any,
    flight_check_list_15: any,


    consumable_check_list_1: any,
    consumable_check_list_2: any,
    consumable_check_list_3: any,
    consumable_check_list_4: any,
    consumable_check_list_5: any,
    consumable_check_list_6: any,
    consumable_check_list_7: any,
    consumable_check_list_8: any,
    consumable_check_list_9: any,
    consumable_check_list_10: any,
    consumable_check_list_11: any,
    consumable_check_list_12: any,
    consumable_check_list_13: any,
    consumable_check_list_14: any,
    consumable_check_list_15: any,
    consumable_check_list_16: any,
    consumable_check_list_17: any,
    consumable_check_list_18: any,
    consumable_check_list_19: any,
    consumable_check_list_20: any,
    consumable_check_list_21: any,
    consumable_check_list_22: any,
    consumable_check_list_23: any,
    consumable_check_list_24: any,
    consumable_check_list_25: any,
    consumable_check_list_26: any,
    consumable_check_list_27: any,

}


export const Auth: React.FC = () => {

          const [myList] = useState<string[]>(["Employee", "Project Lead", "Inventory Lead", "Packer", "Quality Lead"]);
          const [timeLine, setTimeLine] = useState<string>("Employee");
           const [isPortrait, setIsPortrait] = useState(window.matchMedia("(orientation: portrait)").matches);

  useEffect(() => {
    const mediaQuery = window.matchMedia("(orientation: portrait)");

    const handleChange = (e: MediaQueryListEvent) => {
      setIsPortrait(e.matches);
    };

    mediaQuery.addEventListener("change", handleChange);

    return () => {
      mediaQuery.removeEventListener("change", handleChange);
    };
  }, []);
  const packagingRequests: PackagingRequest[] = [
  {
    name: "Request 001",
    employee_id: "E123",
    employee_name: "Abi Chinnasamy",
    package_type: "Ground Components",
    status: "Pending",
    purpose: "Delivery to client",
    transport_from: "Warehouse A",
    transport_to: "Client Site B",
    transport_mode: "Truck",
    packer_name: "John Doe",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager A",
    created_request_date: "2025-10-05",
    created_request_time: "09:30",
    dashboard_status: "Pending",
      ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 002",
    employee_id: "E124",
    employee_name: "Sara Kumar",
    package_type: "Ground Components",
    status: "Project Lead Approved",
    purpose: "Internal transfer",
    transport_from: "Warehouse B",
    transport_to: "Warehouse C",
    transport_mode: "Van",
    packer_name: "Alice Smith",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager B",
    created_request_date: "2025-10-04",
    created_request_time: "14:15",
    dashboard_status: "Pending",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 003",
    employee_id: "E125",
    employee_name: "Ravi Patel",
    package_type: "Flight Components",
    status: "Project Lead Rejected",
    purpose: "Store relocation",
    transport_from: "Warehouse C",
    transport_to: "Warehouse D",
    transport_mode: "Truck",
    packer_name: "David Lee",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager C",
    created_request_date: "2025-10-05",
    created_request_time: "11:00",
    dashboard_status: "Cancelled",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 004",
    employee_id: "E126",
    employee_name: "Meena Iyer",
    package_type: "Ground Components",
    status: "Inventory Lead Approved",
    purpose: "Client shipment",
    transport_from: "Warehouse D",
    transport_to: "Client Site E",
    transport_mode: "Courier",
    packer_name: "Sophia Brown",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager D",
    created_request_date: "2025-10-05",
    created_request_time: "10:45",
    dashboard_status: "Pending",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 005",
    employee_id: "E127",
    employee_name: "Arjun Singh",
    package_type: "Consumable Components",
    status: "Inventory Lead Rejected",
    purpose: "Equipment transfer",
    transport_from: "Warehouse E",
    transport_to: "Warehouse F",
    transport_mode: "Van",
    packer_name: "Emily Clark",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager E",
    created_request_date: "2025-10-03",
    created_request_time: "16:00",
    dashboard_status: "Completed",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },

   {
    name: "Request 006",
    employee_id: "E128",
    employee_name: "Karthik R",
    package_type: "Flight Components",
    status: "Approved for Packaging",
    purpose: "Transfer of bulk goods to main plant",
    transport_from: "Warehouse F",
    transport_to: "Main Factory",
    transport_mode: "Container Truck",
    packer_name: "Robert Taylor",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager F",
    created_request_date: "2025-10-06",
    created_request_time: "08:45",
    dashboard_status: "Pending",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 007",
    employee_id: "E129",
    employee_name: "Priya Menon",
    package_type: "Ground Components",
    status: "Packer Rejected",
    purpose: "Shipment of electronics",
    transport_from: "Warehouse G",
    transport_to: "Client Site F",
    transport_mode: "Air Cargo",
    packer_name: "Laura Green",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager G",
    created_request_date: "2025-10-06",
    created_request_time: "09:15",
    dashboard_status: "Completed",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 008",
    employee_id: "E130",
    employee_name: "Naveen Kumar",
    package_type: "Ground Components",
    status: "Packed",
    purpose: "Relocation of robotic assembly line",
    transport_from: "Plant A",
    transport_to: "Plant B",
    transport_mode: "Truck",
    packer_name: "Oliver Adams",
    image_1: "https://res.cloudinary.com/dababspdo/image/upload/v1759697345/packcomp1_e2p2nd.jpg",
    image_2: "https://res.cloudinary.com/dababspdo/image/upload/v1759697433/packcomp2_xcoeym.jpg",
    image_3: "https://res.cloudinary.com/dababspdo/image/upload/v1759697470/packcomp3_mvvw2l.jpg",
    image_4: "https://res.cloudinary.com/dababspdo/image/upload/v1759697529/packcomp4_jtg0aj.jpg",
    image_5: "https://res.cloudinary.com/dababspdo/image/upload/v1759697555/packcomp5_v2zqx6.jpg",
    image_6: "https://res.cloudinary.com/dababspdo/image/upload/v1759697584/packcomp6_l3nuby.jpg",
    reports_to: "Manager H",
    created_request_date: "2025-10-02",
    created_request_time: "13:00",
    dashboard_status: "Pending",
     ground_check_list_1: true,
    ground_check_list_2: false,
    ground_check_list_3: true,
    ground_check_list_4: false,
    ground_check_list_5: true,
    ground_check_list_6: true,
    ground_check_list_7: false,
    ground_check_list_8: true,
    ground_check_list_9: true,
    ground_check_list_10: false,
    ground_check_list_11: true,
    ground_check_list_12: true,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 009",
    employee_id: "E131",
    employee_name: "Suresh Babu",
    package_type: "Consumable Components",
    status: "Cancelled",
    purpose: "Dispatch of maintenance tools",
    transport_from: "Warehouse H",
    transport_to: "Service Center",
    transport_mode: "Courier",
    packer_name: "Evelyn Wright",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager I",
    created_request_date: "2025-10-06",
    created_request_time: "09:50",
    dashboard_status: "Cancelled",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
  {
    name: "Request 010",
    employee_id: "E132",
    employee_name: "Anita Raj",
    package_type: "Flight Components",
    status: "Quality Lead Approved",
    purpose: "Shipment of lab samples",
    transport_from: "Research Center",
    transport_to: "Testing Lab",
    transport_mode: "Car",
    packer_name: "Henry Ford",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager J",
    created_request_date: "2025-10-06",
    created_request_time: "10:10",
    dashboard_status: "Completed",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
   {
    name: "Request 011",
    employee_id: "E133",
    employee_name: "Rajesh Kumar",
    package_type: "Ground Components",
    status: "Quality Lead Rejected",
    purpose: "Distribution of raw materials",
    transport_from: "Plant A",
    transport_to: "Plant B",
    transport_mode: "Truck",
    packer_name: "George Wilson",
    image_1: null,
    image_2: null,
    image_3: null,
    image_4: null,
    image_5: null,
    image_6: null,
    reports_to: "Manager K",
    created_request_date: "2025-10-01",
    created_request_time: "15:45",
    dashboard_status: "Cancelled",
     ground_check_list_1: null,
    ground_check_list_2: null,
    ground_check_list_3: null,
    ground_check_list_4: null,
    ground_check_list_5: null,
    ground_check_list_6: null,
    ground_check_list_7: null,
    ground_check_list_8: null,
    ground_check_list_9: null,
    ground_check_list_10: null,
    ground_check_list_11: null,
    ground_check_list_12: null,



    flight_check_list_1: null,
    flight_check_list_2: null,
    flight_check_list_3: null,
    flight_check_list_4: null,
    flight_check_list_5: null,
    flight_check_list_6: null,
    flight_check_list_7: null,
    flight_check_list_8: null,
    flight_check_list_9: null,
    flight_check_list_10: null,
    flight_check_list_11: null,
    flight_check_list_12: null,
    flight_check_list_13: null,
    flight_check_list_14: null,
    flight_check_list_15: null,


    consumable_check_list_1: true,
    consumable_check_list_2: null,
    consumable_check_list_3: null,
    consumable_check_list_4: null,
    consumable_check_list_5: null,
    consumable_check_list_6: null,
    consumable_check_list_7: null,
    consumable_check_list_8: null,
    consumable_check_list_9: null,
    consumable_check_list_10: null,
    consumable_check_list_11: null,
    consumable_check_list_12: null,
    consumable_check_list_13: null,
    consumable_check_list_14: null,
    consumable_check_list_15: null,
    consumable_check_list_16: null,
    consumable_check_list_17: null,
    consumable_check_list_18: null,
    consumable_check_list_19: null,
    consumable_check_list_20: null,
    consumable_check_list_21: null,
    consumable_check_list_22: null,
    consumable_check_list_23: null,
    consumable_check_list_24: null,
    consumable_check_list_25: null,
    consumable_check_list_26: null,
    consumable_check_list_27: null,
  },
];
  const navigate = useNavigate();


  const { empdetail, setEmpdetail, setEmployeeRole, setTrackRequest, setQualityApprovalRequestData, setPackagingApprovalRequestData, setInventoryApprovalRequestData, setProjectLeadApprovalRequestData, setPackerLeadApprovalRequestData } = useContext(locateContext);
  useEffect(() => {

          setEmpdetail({
        ...empdetail,
        employee_id: "E123",
        employee_name: "Abinas Chinnasamy",
        reports_to: "managerA@example.com",
        image: "https://res.cloudinary.com/dababspdo/image/upload/v1759703863/dummyphoto_ihmuef.jpg",
      });

      setTrackRequest(packagingRequests);
    
      setQualityApprovalRequestData(packagingRequests);
    
      setPackagingApprovalRequestData(packagingRequests);
    
      setInventoryApprovalRequestData(packagingRequests);
    
      setProjectLeadApprovalRequestData(packagingRequests);
    
  
      setPackerLeadApprovalRequestData(packagingRequests);
    
    }, []); 

  

  // if (isLoading) return <div>loading...</div>;

  // render user
  return (
    <div style={{
      display: "flex",
      justifyContent: "center",
      alignItems: "space-between  ",
flexDirection: isPortrait ? "column" : "row",
      gap: "10px",
    }}>
<div 
style={{
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  gap: "20px",
  marginTop:"50px"
}}>
  <h2>
    Explore By
  </h2>
  <div>

   <FormControl  >
                  <InputLabel id="periods">Role</InputLabel>
                  <Select
                    labelId="periods"
                    id="periods-select"
                    value={timeLine}
                    onChange={(event) => setTimeLine(event.target.value)}
                    label="Periods"
                  >
                    {myList.map(option => (
                      <MenuItem className ="menuItemoption" key={option} value={option}>
                        {option}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
                  </div>
<button 
style={{
width: "100px",
height: "40px",
cursor: "pointer",
}}
                        onClick={() => {setEmployeeRole(timeLine); navigate("/")}}
>
  Login
</button>


      
   

</div>
<div style={{
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  width:"15vw",
  gap: "20px",
  marginTop:"50px"
}}>

</div>
  
                   </div>
  );
};